name: iceberg-tests
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  iceberg-test:
    name: Test lakeFS iceberg catalog
    runs-on: ubuntu-20.04
    env:
      LAKEFS_INSTALLATION_ACCESS_KEY_ID: AKIAIOSFDNN7EXAMPLEQ
      LAKEFS_INSTALLATION_SECRET_ACCESS_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    services:
      lakefs:
        image: "treeverse/lakefs:1"
        ports:
          - '8000:8000'
        env:
          LAKEFS_DATABASE_TYPE: local
          LAKEFS_BLOCKSTORE_TYPE: s3
          LAKEFS_INSTALLATION_ACCESS_KEY_ID: ${{ env.LAKEFS_INSTALLATION_ACCESS_KEY_ID }}
          LAKEFS_INSTALLATION_SECRET_ACCESS_KEY: ${{ env.LAKEFS_INSTALLATION_SECRET_ACCESS_KEY }}
          LAKEFS_BLOCKSTORE_S3_CREDENTIALS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          LAKEFS_BLOCKSTORE_S3_CREDENTIALS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          LAKEFS_AUTH_ENCRYPT_SECRET_KEY: some random secret string
          LAKEFS_STATS_ENABLED: false
          LAKEFS_INSTALLATION_USER_NAME: admin

    steps:
      - name: Check-out code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"
          cache: "maven"
          
      - name: Generate uniquifying value
        id: unique
        run: echo "value=$RANDOM" >> $GITHUB_OUTPUT
        
      - name: Build lakeFS Iceberg
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          STORAGE_NAMESPACE: s3://esti-system-testing/${{ github.run_number }}-iceberg-rest/${{ steps.unique.outputs.value }}
        run: mvn clean install --batch-mode -U -P\!sign-artifacts

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'pip'
      - run: pip install -r ./tests/requirements.txt
          
      - name: Run Python Tests
        run: pip install pytest pytest-md pytest-emoji
      - uses: pavelzw/pytest-action@v2
        env:
          LAKECTL_CREDENTIALS_ACCESS_KEY_ID: ${{ env.LAKEFS_INSTALLATION_ACCESS_KEY_ID }}
          LAKECTL_CREDENTIALS_SECRET_ACCESS_KEY: ${{ env.LAKEFS_INSTALLATION_SECRET_ACCESS_KEY }}
          LAKECTL_SERVER_ENDPOINT_URL: http://localhost:8000
          STORAGE_NAMESPACE: s3://esti-system-testing/${{ github.run_number }}-iceberg-rest/${{ steps.unique.outputs.value }}
        with:
          verbose: true
          emoji: true
          job-summary: true
          custom-arguments: './tests -rP'
          click-to-expand: true
          report-title: 'lakeFS Iceberg Catalog System Tests Report'
